---
- name: 'Provision Image'
  hosts: default
  become: false

  tasks:
    - name: wait for first boot tidyup
      ansible.builtin.pause:
        seconds: 120
    
    - name: reconfigure repositories
      block:
        - name: remove install repo
          community.general.zypper_repository:
            name: openSUSE-Leap-15.2-1
            state: absent

        - name: add main repo
          community.general.zypper_repository:
            name: repo-oss
            repo: 'http://rmt.lab.cypraea.co.uk/repo/distribution/leap/15.2/repo/oss/'
            state: present
            runrefresh: no

        - name: add update repo
          community.general.zypper_repository:
            name: repo-update
            repo: 'http://rmt.lab.cypraea.co.uk/repo/update/leap/15.2/oss/'
            state: present
            runrefresh: no

    - name: freshen packages
      block:
        - name: refresh repositories
          zypper_repository:
            repo: '*'
            runrefresh: yes
    
        - name: update all patches
          community.general.zypper:
            name: '*'
            state: latest

    - name: include cloud-init
      block:
        - name: install cloud-init
          community.general.zypper:
            name: 'cloud-init'
            state: latest

        - name: setup cloud-init
          ansible.builtin.systemd:
            name: cloud-init
            enabled: yes 

    - name: reset machine-id
      block:
        - name: remove machine-id
          ansible.builtin.copy:
            content: ''
            dest: /etc/machine-id
            force: yes
            owner: root
            group: root
            mode: '0444'
    
        - name: check dbus machine-id symlink
          ansible.builtin.file:
            path: /var/lib/dbus/machine-id
            src: /etc/machine-id
            state: link

    - name: clean wicked iaid, duid, etc
      block:
        - name: find wicked xml stuff
          ansible.builtin.find:
            paths: /var/lib/wicked/
            patterns: '*.xml'
          register: wicked_xml_crap
  
        - name: delete found wicked xml stuff
          ansible.builtin.file:
            path: '{{ item.path }}'
            state: absent
          with_items: '{{ wicked_xml_crap.files }}'

    - name: extra time
      ansible.builtin.pause:
        seconds: 120
